// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: report_management.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetSpendingReport(ctx context.Context, in *GetSpendingReportRequest, opts ...grpc.CallOption) (*SpendingReportResponse, error)
	GetIncomeReport(ctx context.Context, in *GetIncomeReportRequest, opts ...grpc.CallOption) (*IncomeReportResponse, error)
	GetBudgetPerformanceReport(ctx context.Context, in *GetBudgetPerformanceReportRequest, opts ...grpc.CallOption) (*BudgetPerformanceReportResponse, error)
	GetGoalProgressReport(ctx context.Context, in *GetGoalProgressReportRequest, opts ...grpc.CallOption) (*GoalProgressReportResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetSpendingReport(ctx context.Context, in *GetSpendingReportRequest, opts ...grpc.CallOption) (*SpendingReportResponse, error) {
	out := new(SpendingReportResponse)
	err := c.cc.Invoke(ctx, "/budget.ReportService/GetSpendingReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetIncomeReport(ctx context.Context, in *GetIncomeReportRequest, opts ...grpc.CallOption) (*IncomeReportResponse, error) {
	out := new(IncomeReportResponse)
	err := c.cc.Invoke(ctx, "/budget.ReportService/GetIncomeReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetBudgetPerformanceReport(ctx context.Context, in *GetBudgetPerformanceReportRequest, opts ...grpc.CallOption) (*BudgetPerformanceReportResponse, error) {
	out := new(BudgetPerformanceReportResponse)
	err := c.cc.Invoke(ctx, "/budget.ReportService/GetBudgetPerformanceReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetGoalProgressReport(ctx context.Context, in *GetGoalProgressReportRequest, opts ...grpc.CallOption) (*GoalProgressReportResponse, error) {
	out := new(GoalProgressReportResponse)
	err := c.cc.Invoke(ctx, "/budget.ReportService/GetGoalProgressReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	GetSpendingReport(context.Context, *GetSpendingReportRequest) (*SpendingReportResponse, error)
	GetIncomeReport(context.Context, *GetIncomeReportRequest) (*IncomeReportResponse, error)
	GetBudgetPerformanceReport(context.Context, *GetBudgetPerformanceReportRequest) (*BudgetPerformanceReportResponse, error)
	GetGoalProgressReport(context.Context, *GetGoalProgressReportRequest) (*GoalProgressReportResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) GetSpendingReport(context.Context, *GetSpendingReportRequest) (*SpendingReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpendingReport not implemented")
}
func (UnimplementedReportServiceServer) GetIncomeReport(context.Context, *GetIncomeReportRequest) (*IncomeReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeReport not implemented")
}
func (UnimplementedReportServiceServer) GetBudgetPerformanceReport(context.Context, *GetBudgetPerformanceReportRequest) (*BudgetPerformanceReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetPerformanceReport not implemented")
}
func (UnimplementedReportServiceServer) GetGoalProgressReport(context.Context, *GetGoalProgressReportRequest) (*GoalProgressReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoalProgressReport not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetSpendingReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpendingReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSpendingReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/budget.ReportService/GetSpendingReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSpendingReport(ctx, req.(*GetSpendingReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetIncomeReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetIncomeReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/budget.ReportService/GetIncomeReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetIncomeReport(ctx, req.(*GetIncomeReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetBudgetPerformanceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetPerformanceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetBudgetPerformanceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/budget.ReportService/GetBudgetPerformanceReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetBudgetPerformanceReport(ctx, req.(*GetBudgetPerformanceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetGoalProgressReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalProgressReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetGoalProgressReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/budget.ReportService/GetGoalProgressReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetGoalProgressReport(ctx, req.(*GetGoalProgressReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "budget.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpendingReport",
			Handler:    _ReportService_GetSpendingReport_Handler,
		},
		{
			MethodName: "GetIncomeReport",
			Handler:    _ReportService_GetIncomeReport_Handler,
		},
		{
			MethodName: "GetBudgetPerformanceReport",
			Handler:    _ReportService_GetBudgetPerformanceReport_Handler,
		},
		{
			MethodName: "GetGoalProgressReport",
			Handler:    _ReportService_GetGoalProgressReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report_management.proto",
}
