// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: report_management.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSpendingReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetSpendingReportRequest) Reset() {
	*x = GetSpendingReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpendingReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingReportRequest) ProtoMessage() {}

func (x *GetSpendingReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingReportRequest.ProtoReflect.Descriptor instead.
func (*GetSpendingReportRequest) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{0}
}

func (x *GetSpendingReportRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetSpendingReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetIncomeReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetIncomeReportRequest) Reset() {
	*x = GetIncomeReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeReportRequest) ProtoMessage() {}

func (x *GetIncomeReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeReportRequest.ProtoReflect.Descriptor instead.
func (*GetIncomeReportRequest) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetIncomeReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetIncomeReportRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBudgetPerformanceReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBudgetPerformanceReportRequest) Reset() {
	*x = GetBudgetPerformanceReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBudgetPerformanceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetPerformanceReportRequest) ProtoMessage() {}

func (x *GetBudgetPerformanceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetPerformanceReportRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetPerformanceReportRequest) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetBudgetPerformanceReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGoalProgressReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetGoalProgressReportRequest) Reset() {
	*x = GetGoalProgressReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoalProgressReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalProgressReportRequest) ProtoMessage() {}

func (x *GetGoalProgressReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalProgressReportRequest.ProtoReflect.Descriptor instead.
func (*GetGoalProgressReportRequest) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoalProgressReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SpendingReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSpent float64 `protobuf:"fixed64,1,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
}

func (x *SpendingReportResponse) Reset() {
	*x = SpendingReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendingReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingReportResponse) ProtoMessage() {}

func (x *SpendingReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingReportResponse.ProtoReflect.Descriptor instead.
func (*SpendingReportResponse) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{4}
}

func (x *SpendingReportResponse) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

type IncomeReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalIncome float64 `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
}

func (x *IncomeReportResponse) Reset() {
	*x = IncomeReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncomeReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeReportResponse) ProtoMessage() {}

func (x *IncomeReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeReportResponse.ProtoReflect.Descriptor instead.
func (*IncomeReportResponse) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{5}
}

func (x *IncomeReportResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

type BudgetPerformanceReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalBudget float64 `protobuf:"fixed64,1,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	TotalSpent  float64 `protobuf:"fixed64,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
}

func (x *BudgetPerformanceReportResponse) Reset() {
	*x = BudgetPerformanceReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BudgetPerformanceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetPerformanceReportResponse) ProtoMessage() {}

func (x *BudgetPerformanceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetPerformanceReportResponse.ProtoReflect.Descriptor instead.
func (*BudgetPerformanceReportResponse) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{6}
}

func (x *BudgetPerformanceReportResponse) GetTotalBudget() float64 {
	if x != nil {
		return x.TotalBudget
	}
	return 0
}

func (x *BudgetPerformanceReportResponse) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

type GoalProgressReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalGoalAmount float64 `protobuf:"fixed64,1,opt,name=total_goal_amount,json=totalGoalAmount,proto3" json:"total_goal_amount,omitempty"`
	TotalSaved      float64 `protobuf:"fixed64,2,opt,name=total_saved,json=totalSaved,proto3" json:"total_saved,omitempty"`
}

func (x *GoalProgressReportResponse) Reset() {
	*x = GoalProgressReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_report_management_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoalProgressReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalProgressReportResponse) ProtoMessage() {}

func (x *GoalProgressReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_management_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalProgressReportResponse.ProtoReflect.Descriptor instead.
func (*GoalProgressReportResponse) Descriptor() ([]byte, []int) {
	return file_report_management_proto_rawDescGZIP(), []int{7}
}

func (x *GoalProgressReportResponse) GetTotalGoalAmount() float64 {
	if x != nil {
		return x.TotalGoalAmount
	}
	return 0
}

func (x *GoalProgressReportResponse) GetTotalSaved() float64 {
	if x != nil {
		return x.TotalSaved
	}
	return 0
}

var File_report_management_proto protoreflect.FileDescriptor

var file_report_management_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x22, 0x52, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x39,
	0x0a, 0x16, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x39, 0x0a, 0x14, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x1f, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x50, 0x65,
	0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x69, 0x0a, 0x1a, 0x47,
	0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x67, 0x6f, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x47, 0x6f, 0x61, 0x6c, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x61, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x61, 0x76, 0x65, 0x64, 0x32, 0x8c, 0x03, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x2e,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x1e, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x70, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x50, 0x65, 0x72,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x29,
	0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x61, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x2e, 0x62, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_report_management_proto_rawDescOnce sync.Once
	file_report_management_proto_rawDescData = file_report_management_proto_rawDesc
)

func file_report_management_proto_rawDescGZIP() []byte {
	file_report_management_proto_rawDescOnce.Do(func() {
		file_report_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_report_management_proto_rawDescData)
	})
	return file_report_management_proto_rawDescData
}

var file_report_management_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_report_management_proto_goTypes = []interface{}{
	(*GetSpendingReportRequest)(nil),          // 0: budget.GetSpendingReportRequest
	(*GetIncomeReportRequest)(nil),            // 1: budget.GetIncomeReportRequest
	(*GetBudgetPerformanceReportRequest)(nil), // 2: budget.GetBudgetPerformanceReportRequest
	(*GetGoalProgressReportRequest)(nil),      // 3: budget.GetGoalProgressReportRequest
	(*SpendingReportResponse)(nil),            // 4: budget.SpendingReportResponse
	(*IncomeReportResponse)(nil),              // 5: budget.IncomeReportResponse
	(*BudgetPerformanceReportResponse)(nil),   // 6: budget.BudgetPerformanceReportResponse
	(*GoalProgressReportResponse)(nil),        // 7: budget.GoalProgressReportResponse
}
var file_report_management_proto_depIdxs = []int32{
	0, // 0: budget.ReportService.GetSpendingReport:input_type -> budget.GetSpendingReportRequest
	1, // 1: budget.ReportService.GetIncomeReport:input_type -> budget.GetIncomeReportRequest
	2, // 2: budget.ReportService.GetBudgetPerformanceReport:input_type -> budget.GetBudgetPerformanceReportRequest
	3, // 3: budget.ReportService.GetGoalProgressReport:input_type -> budget.GetGoalProgressReportRequest
	4, // 4: budget.ReportService.GetSpendingReport:output_type -> budget.SpendingReportResponse
	5, // 5: budget.ReportService.GetIncomeReport:output_type -> budget.IncomeReportResponse
	6, // 6: budget.ReportService.GetBudgetPerformanceReport:output_type -> budget.BudgetPerformanceReportResponse
	7, // 7: budget.ReportService.GetGoalProgressReport:output_type -> budget.GoalProgressReportResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_management_proto_init() }
func file_report_management_proto_init() {
	if File_report_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_report_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpendingReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBudgetPerformanceReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoalProgressReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendingReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncomeReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BudgetPerformanceReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_report_management_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoalProgressReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_report_management_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_management_proto_goTypes,
		DependencyIndexes: file_report_management_proto_depIdxs,
		MessageInfos:      file_report_management_proto_msgTypes,
	}.Build()
	File_report_management_proto = out.File
	file_report_management_proto_rawDesc = nil
	file_report_management_proto_goTypes = nil
	file_report_management_proto_depIdxs = nil
}
